
apiVersion: 1

datasources:
  - name: Aggregate Reports
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "aggregate_reports-*"
    jsonData:
      timeField: "report_date"

  - name: Forensic Reports
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "forensic_reports-*"
    jsonData:
      timeField: "report_date"
