apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    database: "aggregate_reports"
    jsonData:
      esVersion: "7.17.0"
      timeField: "report_date"
      interval: "Daily"
    version: 1
    editable: true