{
 "title": "DMARCレポート概要",
 "time": { "from": "2024-10-09T02:59:57.500Z", "to": "2024-10-10T02:59:56.500Z" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "domain",
    "query": "{\"find\": \"terms\", \"field\": \"policy_published.domain\", \"size\": 100}"
   }
  ]
 },
 "panels": [
  {
   "title": "現在の分析対象ドメイン情報",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain})",
     "queryText": "WITH domain_info AS (\r\n    SELECT \r\n        substr(f.from_address, instr(f.from_address, '@') + 1) as domain,\r\n        COUNT(DISTINCT f.source_ip) as unique_ips,\r\n        COUNT(*) as report_count,\r\n        COUNT(DISTINCT a.organization) as org_count,\r\n        SUM(a.count) as total_mails,\r\n        date(min(f.created_at)) as start_date,\r\n        date(max(f.created_at)) as end_date\r\n    FROM dmarc_forensic f\r\n    LEFT JOIN dmarc_aggregate a ON f.source_ip = a.source_ip\r\n    GROUP BY substr(f.from_address, instr(f.from_address, '@') + 1)\r\n)\r\nSELECT \r\n    domain as \"分析対象ドメイン\",\r\n    org_count as \"レポート送信組織数\",\r\n    unique_ips as \"送信元IP数\",\r\n    report_count as \"レポート数\",\r\n    total_mails as \"総メール数\",\r\n    start_date as \"データ開始日\",\r\n    end_date as \"データ最終日\"\r\nFROM domain_info\r\nORDER BY total_mails DESC;",
     "rawQueryText": "WITH domain_info AS (\r\n    SELECT \r\n        substr(f.from_address, instr(f.from_address, '@') + 1) as domain,\r\n        COUNT(DISTINCT f.source_ip) as unique_ips,\r\n        COUNT(*) as report_count,\r\n        COUNT(DISTINCT a.organization) as org_count,\r\n        SUM(a.count) as total_mails,\r\n        date(min(f.created_at)) as start_date,\r\n        date(max(f.created_at)) as end_date\r\n    FROM dmarc_forensic f\r\n    LEFT JOIN dmarc_aggregate a ON f.source_ip = a.source_ip\r\n    GROUP BY substr(f.from_address, instr(f.from_address, '@') + 1)\r\n)\r\nSELECT \r\n    domain as \"分析対象ドメイン\",\r\n    org_count as \"レポート送信組織数\",\r\n    unique_ips as \"送信元IP数\",\r\n    report_count as \"レポート数\",\r\n    total_mails as \"総メール数\",\r\n    start_date as \"データ開始日\",\r\n    end_date as \"データ最終日\"\r\nFROM domain_info\r\nORDER BY total_mails DESC;",
     "timeColumns": [
      "time",
      "ts"
     ],
     "timeField": "report_date"
    }
   ]
  },
  {
   "title": "メールの到達率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "spf&dkim",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND (policy_evaluated.dkim:pass AND policy_evaluated.spf:pass)",
     "queryText": "WITH domain_info AS (\r\n    SELECT \r\n        substr(f.from_address, instr(f.from_address, '@') + 1) as domain,\r\n        COUNT(DISTINCT f.source_ip) as unique_ips,\r\n        COUNT(*) as report_count,\r\n        COUNT(DISTINCT a.organization) as org_count,\r\n        SUM(a.count) as total_mails,\r\n        date(min(f.created_at)) as start_date,\r\n        date(max(f.created_at)) as end_date\r\n    FROM dmarc_forensic f\r\n    LEFT JOIN dmarc_aggregate a ON f.source_ip = a.source_ip\r\n    GROUP BY substr(f.from_address, instr(f.from_address, '@') + 1)\r\n)\r\nSELECT \r\n    domain as \"分析対象ドメイン\",\r\n    org_count as \"レポート送信組織数\",\r\n    unique_ips as \"送信元IP数\",\r\n    report_count as \"レポート数\",\r\n    total_mails as \"総メール数\",\r\n    start_date as \"データ開始日\",\r\n    end_date as \"データ最終日\"\r\nFROM domain_info\r\nORDER BY total_mails DESC;",
     "rawQueryText": "WITH domain_info AS (\r\n    SELECT \r\n        substr(f.from_address, instr(f.from_address, '@') + 1) as domain,\r\n        COUNT(DISTINCT f.source_ip) as unique_ips,\r\n        COUNT(*) as report_count,\r\n        COUNT(DISTINCT a.organization) as org_count,\r\n        SUM(a.count) as total_mails,\r\n        date(min(f.created_at)) as start_date,\r\n        date(max(f.created_at)) as end_date\r\n    FROM dmarc_forensic f\r\n    LEFT JOIN dmarc_aggregate a ON f.source_ip = a.source_ip\r\n    GROUP BY substr(f.from_address, instr(f.from_address, '@') + 1)\r\n)\r\nSELECT \r\n    domain as \"分析対象ドメイン\",\r\n    org_count as \"レポート送信組織数\",\r\n    unique_ips as \"送信元IP数\",\r\n    report_count as \"レポート数\",\r\n    total_mails as \"総メール数\",\r\n    start_date as \"データ開始日\",\r\n    end_date as \"データ最終日\"\r\nFROM domain_info\r\nORDER BY total_mails DESC;",
     "timeColumns": [
      "time",
      "ts"
     ],
     "timeField": "report_date"
    },
    {
     "alias": "Email total",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain})",
     "timeField": "report_date"
    }
   ]
  },
  {
   "title": "SPFとDKIMの合計で計算したエラー率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Total Count",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain})",
     "queryText": "WITH domain_info AS (\r\n    SELECT \r\n        substr(f.from_address, instr(f.from_address, '@') + 1) as domain,\r\n        COUNT(DISTINCT f.source_ip) as unique_ips,\r\n        COUNT(*) as report_count,\r\n        COUNT(DISTINCT a.organization) as org_count,\r\n        SUM(a.count) as total_mails,\r\n        date(min(f.created_at)) as start_date,\r\n        date(max(f.created_at)) as end_date\r\n    FROM dmarc_forensic f\r\n    LEFT JOIN dmarc_aggregate a ON f.source_ip = a.source_ip\r\n    GROUP BY substr(f.from_address, instr(f.from_address, '@') + 1)\r\n)\r\nSELECT \r\n    domain as \"分析対象ドメイン\",\r\n    org_count as \"レポート送信組織数\",\r\n    unique_ips as \"送信元IP数\",\r\n    report_count as \"レポート数\",\r\n    total_mails as \"総メール数\",\r\n    start_date as \"データ開始日\",\r\n    end_date as \"データ最終日\"\r\nFROM domain_info\r\nORDER BY total_mails DESC;",
     "rawQueryText": "WITH domain_info AS (\r\n    SELECT \r\n        substr(f.from_address, instr(f.from_address, '@') + 1) as domain,\r\n        COUNT(DISTINCT f.source_ip) as unique_ips,\r\n        COUNT(*) as report_count,\r\n        COUNT(DISTINCT a.organization) as org_count,\r\n        SUM(a.count) as total_mails,\r\n        date(min(f.created_at)) as start_date,\r\n        date(max(f.created_at)) as end_date\r\n    FROM dmarc_forensic f\r\n    LEFT JOIN dmarc_aggregate a ON f.source_ip = a.source_ip\r\n    GROUP BY substr(f.from_address, instr(f.from_address, '@') + 1)\r\n)\r\nSELECT \r\n    domain as \"分析対象ドメイン\",\r\n    org_count as \"レポート送信組織数\",\r\n    unique_ips as \"送信元IP数\",\r\n    report_count as \"レポート数\",\r\n    total_mails as \"総メール数\",\r\n    start_date as \"データ開始日\",\r\n    end_date as \"データ最終日\"\r\nFROM domain_info\r\nORDER BY total_mails DESC;",
     "timeColumns": [
      "time",
      "ts"
     ],
     "timeField": "report_date"
    },
    {
     "alias": "Error Count",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND (policy_evaluated.dkim:(\"fail\" OR \"neutral\" OR \"softfail\") OR policy_evaluated.spf:(\"fail\" OR \"neutral\" OR \"softfail\"))",
     "timeField": "report_date"
    }
   ]
  },
  {
   "title": "注意事項",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "グラフの表示でNaNが表示されるときは、集計期間を調整してください。"
   }
  },
  {
   "title": "DMARC認証結果の日次推移",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "SPF成功件数",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND (policy_evaluated.spf:pass)",
     "queryText": "SELECT \n    date(created_at) || ' 00:00:00' as \"time\",\n    organization as \"組織\",\n    SUM(CASE WHEN spf_result != 'pass' THEN count ELSE 0 END) as \"SPFエラー数\",\n    SUM(CASE WHEN dkim_result != 'pass' THEN count ELSE 0 END) as \"DKIMエラー数\",\n    ROUND(SUM(CASE WHEN spf_result = 'pass' THEN count ELSE 0 END) * 100.0 / SUM(count), 2) as \"SPF成功率\",\n    ROUND(SUM(CASE WHEN dkim_result = 'pass' THEN count ELSE 0 END) * 100.0 / SUM(count), 2) as \"DKIM成功率\"\nFROM dmarc_aggregate\nGROUP BY date(created_at), organization\nORDER BY time;",
     "rawQueryText": "SELECT \n    date(created_at) || ' 00:00:00' as \"time\",\n    organization as \"組織\",\n    SUM(CASE WHEN spf_result != 'pass' THEN count ELSE 0 END) as \"SPFエラー数\",\n    SUM(CASE WHEN dkim_result != 'pass' THEN count ELSE 0 END) as \"DKIMエラー数\",\n    ROUND(SUM(CASE WHEN spf_result = 'pass' THEN count ELSE 0 END) * 100.0 / SUM(count), 2) as \"SPF成功率\",\n    ROUND(SUM(CASE WHEN dkim_result = 'pass' THEN count ELSE 0 END) * 100.0 / SUM(count), 2) as \"DKIM成功率\"\nFROM dmarc_aggregate\nGROUP BY date(created_at), organization\nORDER BY time;",
     "timeColumns": [
      "time",
      "ts"
     ],
     "timeField": "report_date"
    },
    {
     "alias": "DKIM成功件数",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.dkim:pass",
     "timeField": "report_date"
    },
    {
     "alias": "SPFエラー数",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.spf:fail",
     "timeField": "report_date"
    },
    {
     "alias": "DKIMエラー数",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND auth_results.dkim:fail",
     "timeField": "report_date"
    },
    {
     "alias": "メール総数",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain})",
     "timeField": "report_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "### DMARC認証についての解説\n- **SPF成功率**: SPF認証で合格したメールの割合\n- **DKIM成功率**: DKIM認証で合格したメールの割合\n- **ソフトフェイル (Softfail)**: SPFが完全に失敗せず、警告として扱われる\n- **ポリシー評価 (Disposition)**: メールの取り扱いに関する最終的な決定（例: `quarantine`や`reject`）\n"
   }
  },
  {
   "title": "SPF/DKIMの詳細なステータス",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "spf:fail",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND auth_results.spf:fail",
     "timeField": "report_date"
    },
    {
     "alias": "dkim:fail",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND auth_results.dkim:fail",
     "timeField": "report_date"
    },
    {
     "alias": "spf:softfail",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.spf:softfail",
     "timeField": "report_date"
    },
    {
     "alias": "dkim:neutral",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.dkim:neutral",
     "timeField": "report_date"
    },
    {
     "alias": "ポリシー：監視",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.disposition:none",
     "timeField": "report_date"
    },
    {
     "alias": "ポリシー：隔離",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.disposition:quarantine",
     "timeField": "report_date"
    },
    {
     "alias": "ポリシー：拒否",
     "bucketAggs": [
      { "field": "report_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "policy_published.domain:(${domain}) AND policy_evaluated.disposition:reject",
     "timeField": "report_date"
    }
   ]
  }
 ]
}